### ISSUE TITLE
TypeError: Cannot set property 'atrulers_end' of undefined

### ISSUE THREAD

**Issue by tkazec** [lesshint/lesshint#122]
Trying to set up lesshint for the first time, seems to run along nicely, then throws these fairly cryptic messages:

```
Syntax "undefined" is not supported yet, sorry
Syntax "undefined" is not supported yet, sorry
An unkown error occured, please file an issue with this info:
TypeError: Cannot set property 'atrulers_end' of undefined
    at checkAtrulers (xxx/node_modules/lesshint/node_modules/gonzales-pe/lib/less/parse.js:554:26)
    at checkAtruler (xxx/node_modules/lesshint/node_modules/gonzales-pe/lib/less/parse.js:516:11)
    at checkAtrule (xxx/node_modules/lesshint/node_modules/gonzales-pe/lib/less/parse.js:439:73)
    at checkStylesheet (xxx/node_modules/lesshint/node_modules/gonzales-pe/lib/less/parse.js:2895:27)
    at Object.contexts.stylesheet (xxx/node_modules/lesshint/node_modules/gonzales-pe/lib/less/parse.js:132:12)
    at module.exports (xxx/node_modules/lesshint/node_modules/gonzales-pe/lib/less/parse.js:3238:27)
    at Object.parser [as parse] (xxx/node_modules/lesshint/node_modules/gonzales-pe/lib/parse.js:36:11)
    at Object.exports.parseAST (xxx/node_modules/lesshint/lib/linter.js:113:21)
    at Object.exports.lint (xxx/node_modules/lesshint/lib/linter.js:57:16)
    at Lesshint.checkString (xxx/node_modules/lesshint/lib/lesshint.js:67:25)
    at null.<anonymous> (xxx/node_modules/lesshint/lib/lesshint.js:47:21)
```

I'd be happy to provide the code causing this to fail, if I knew which part it was.

**Comment by jwilsson** [comment]
Hmm, it almost sounds like you have some Less that's invalid/faulty.

Something involving an @-rule, I'm afraid that's all I can tell you. If you managed to track it down and it's valid, please report back and we'll investigate more!

**Comment by shellscape** [comment]
@tkazec definitely an issue with a dependency called gonzales-pe. We've been fighting these kinds of errors since they released a new version that really screwed up LESS support in the module (SCSS was equally as effected).

If you can figure out what block of code is causing that error, I can probably produce a fix in our fork of gonzales-pe we're using for LESS fixes. Process of elimination will work best here - start a file a time until the offending one throws the error. Then start commenting out chunks of the file and drill down from there to smaller chunks. Should arrive at the offender pretty quickly.

**Comment by tkazec** [comment]
Hi all, my bad, I was accidentally analyzing my entire `node_modules` folder... Stupid 2am mistake :( Found it pretty quickly, but it'd be nice to have a debug/verbose mode to print each filename lesshint is analyzing.

**Comment by shellscape** [comment]
That's a good suggestion :+1:
