### ISSUE TITLE
error with 1.5.0

### ISSUE THREAD

**Issue by wareczek** [lesshint/lesshint#164]
```
An unkown error occured, please file an issue with this info:
TypeError: Cannot read property 'content' of null
    at Object.zeroUnitLinter [as lint] (/usr/lib/node_modules/lesshint/lib/linters/zero_unit.js:19:61)
    at /usr/lib/node_modules/lesshint/lib/linter.js:140:32
    at Array.forEach (native)
    at /usr/lib/node_modules/lesshint/lib/linter.js:126:17
    at Node.traverse (/usr/lib/node_modules/lesshint/node_modules/gonzales-pe/lib/node/basic-node.js:207:5)
    at Node.traverse (/usr/lib/node_modules/lesshint/node_modules/gonzales-pe/lib/node/basic-node.js:212:35)
    at Node.traverse (/usr/lib/node_modules/lesshint/node_modules/gonzales-pe/lib/node/basic-node.js:212:35)
    at Node.traverse (/usr/lib/node_modules/lesshint/node_modules/gonzales-pe/lib/node/basic-node.js:212:35)
    at Object.exports.lint (/usr/lib/node_modules/lesshint/lib/linter.js:125:9)
    at Lesshint.checkString (/usr/lib/node_modules/lesshint/lib/lesshint.js:67:25)
```

simple less mixin:
```
.background-image(@bar-width: 160px) {
    border: 1px solid red;
}
```

**Comment by shellscape** [comment]
@jwilsson @kokarn looks like we need a fix patch published guys

**Comment by jwilsson** [comment]
Sorry guys, was out of town for Easter. I've just pushed `1.5.1`.
