### ISSUE TITLE
Unknown error: Cannot read property 'valueOf' of undefined

### ISSUE THREAD

**Issue by tkazec** [lesshint/lesshint#192]
Ran lesshint@next on a file that worked in 1.5.2, and got this:

```
An unkown error occured, please file an issue with this info:
TypeError: Cannot read property 'valueOf' of undefined
    at tokenize (postcss-values-parser/dist/tokenize.js:35:18)
    at new Parser (postcss-values-parser/dist/parser.js:95:42)
    at parser (postcss-values-parser/dist/index.js:56:10)
    at Object.urlQuotesLinter [as lint] (lesshint/lib/linters/url_quotes.js:11:19)
    at lesshint/lib/linter.js:132:32
    at Array.forEach (native)
    at lesshint/lib/linter.js:118:17
    at postcss/lib/container.js:81:26
    at Root.each (postcss/lib/container.js:68:22)
    at Root.walk (postcss/lib/container.js:80:21)
```

Not sure where to start looking since it's a large file and the error message has no specific debug info.

**Comment by jwilsson** [comment]
Thanks for the report!

I think I know what it's caused by, do you have any at-rules without a prelude, a `@font-face` for example?

**Comment by tkazec** [comment]
The only "@-rules" we have are variables and imports like:

```less
@import "bootswatch/flatly/variables";
@navbar-default-color: @gray-light;
```

But those are both actually LESS.

**Comment by jwilsson** [comment]
Hmm, I tested some things and it fails when there's no `params` or `value` on the `Node`. I'll add an extra check for it.

**Comment by tkazec** [comment]
Hi, has this been pushed to `@next`?
