### ISSUE TITLE
Unknown error: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by tkazec** [lesshint/lesshint#215]
Ran lesshint 2.0.0 w/ Node 6.3.0 on a file that worked in 1.5.2, and got this:

```
An unkown error occured, please file an issue with this info:
TypeError: Cannot read property 'value' of undefined
    at Parser.parentheses (postcss-selector-parser/dist/parser.js:296:17)
    at Parser.parse (postcss-selector-parser/dist/parser.js:522:22)
    at Parser.loop (postcss-selector-parser/dist/parser.js:508:18)
    at new Parser (postcss-selector-parser/dist/parser.js:99:21)
    at Processor.process (postcss-selector-parser/dist/processor.js:24:21)
    at Object.attributeQuotesLinter [as lint] (lesshint/lib/linters/attribute_quotes.js:33:12)
    at lesshint/lib/linter.js:154:32
    at Array.forEach (native)
    at lesshint/lib/linter.js:125:17
    at postcss/lib/container.js:164:26
```

Not sure where to start looking since it's a large file and the error message has no specific debug info.

**Comment by shellscape** [comment]
hm, looks like postcss-selector-parser is to blame there. you can go with the tedious method of commenting out blocks of that file until you narrow the selector(s) responsible, or you could use a paste website or gist to post the file that's throwing the error. without that, there's little we can do unfortunately.

**Comment by tkazec** [comment]
Closing because this was actually due to a change (?) in `excludedFiles` handling, leading to lesshint trying to parse all of bootstrap. Works fine after adjusting the excluded paths.

(It would be really helpful if lesshint could identify the file path when it trips up though.)

**Comment by shellscape** [comment]
We'd definitely welcome a contribution adding that info.
