### ISSUE TITLE
Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by vitalyiegorov** [lesshint/lesshint#259]
Installed latest version through npm, when try to run for our project I get this error:
lesshint src/
An unkown error occured, please file an issue with this info:
TypeError: Cannot read property 'source' of undefined
    at Object.finalNewlineLinter [as lint](/usr/local/lib/node_modules/lesshint/lib/linters/final_newline.js:12:63)
    at /usr/local/lib/node_modules/lesshint/lib/linter.js:134:32
    at Array.forEach (native)
    at checkNode (/usr/local/lib/node_modules/lesshint/lib/linter.js:105:17)
    at runChecks (/usr/local/lib/node_modules/lesshint/lib/linter.js:200:5)
    at Object.exports.lint (/usr/local/lib/node_modules/lesshint/lib/linter.js:248:19)
    at Lesshint.checkString (/usr/local/lib/node_modules/lesshint/lib/lesshint.js:66:25)
    at null.<anonymous> (/usr/local/lib/node_modules/lesshint/lib/lesshint.js:47:21)
    at Array.<anonymous> (/usr/local/lib/node_modules/lesshint/node_modules/vow/lib/vow.js:712:39)
    at Immediate.callFns [as _onImmediate](/usr/local/lib/node_modules/lesshint/node_modules/vow/lib/vow.js:23:35)

**Comment by shellscape** [comment]
(did you have your entire team thumbs-up your post? lol)

we'll need to see some LESS source from your project to debug this, since all of the specs are running in CI and locally. also, I modified the name of your issue to something a bit more identifiable.

**Comment by vitalyiegorov** [comment]
@shellscape Yes, to attract your attention)

Can I send you just zip with all less files?

**Comment by jwilsson** [comment]
@vitalyiegorov Could you recheck with the changes proposed in https://github.com/lesshint/lesshint/pull/262 and get back to us with the contents of the file reported there? Thanks!

**Comment by jwilsson** [comment]
Closing this due to a lack of info. 

@vitalyiegorov Please reopen if you got more info!
