### ISSUE TITLE
Causes runtime error when using comma instead of semicolon in less file

### ISSUE THREAD

**Issue by KennyLindahl** [lesshint/lesshint#318]
**Usage info**
- Lesshint version 2.1.1 and 2.4.0 (Using Node API)
- Config: Basically empty (which means i'm using the default since it's merged with it): {}

**What did you expect to happen?**
It should report like normal and not cause a runtime error, for example: 
"Expected ; got ,"

**What's the actual result?**
`
tasks.js:190 TypeError: Cannot read property 'raws' of undefined
	at /project/node_modules/lesshint/lib/linters/space_around_comma.js:65:29
	at /project/node_modules/postcss-values-parser/dist/container.js:66:20
	at Value.each (/project/node_modules/postcss-values-parser/dist/container.js:53:16)
	at Value.walk (/project/node_modules/postcss-values-parser/dist/container.js:65:17)
	at /project/node_modules/postcss-values-parser/dist/container.js:68:24
	at Root.each (/project/node_modules/postcss-values-parser/dist/container.js:53:16)
	at Root.walk (/project/node_modules/postcss-values-parser/dist/container.js:65:17)
	at Object.spaceAroundCommaLinter [as lint] (/project/node_modules/lesshint/lib/linters/space_around_comma.js:27:13)
	at /project/node_modules/lesshint/lib/linter.js:134:32
	at Array.forEach (native)
	at checkNode (/project/node_modules/lesshint/lib/linter.js:105:17)
	at /project/node_modules/lesshint/lib/linter.js:204:9
	at /project/node_modules/postcss/lib/container.js:148:26
	at Rule.each (/project/node_modules/postcss/lib/container.js:114:22)
	at Rule.walk (/project/node_modules/postcss/lib/container.js:147:21)
	at /project/node_modules/postcss/lib/container.js:150:32
	at /project/node_modules/postcss/lib/container.js:150:32
`

**The less file looks like this:**
`
.property {
    background: red,
}
`

**Comment by shellscape** [comment]
@KennyLindahl (currently in transit atm) can you point to the LESS docs for the comma-instead-of-semicolon pattern?

**Comment by KennyLindahl** [comment]
@shellscape I don't know if there is a pattern for that, but the most important this is that it should not crash in JS because of syntax in a less file. But i would expect it to say "expecting semicolon", but this is not required.

**Comment by shellscape** [comment]
well we wouldn't want to show an error about a semicolon, because that's for a rule to define. this is an object reference error in Lesshint, and a parser issue beyond that.

**Comment by KennyLindahl** [comment]
@shellscape @jwilsson Please have a look at @burnall PR so this issue could be fixed :)
He just did some very minor code changes and added a test for it, so it should be a quick review.
