### ISSUE TITLE
Linter fails on logical OR

### ISSUE THREAD

**Issue by Igloczek** [lesshint/lesshint#436]
Code containing logical OR, which in LESS is just a comma, is failing the linting process.

I'm using v4.1.3 on Node v6.10.3 via CLI (I tried also a Gulp plugin, but it returns same issues) and with default config (no .lesshintrc).

LESS code samples:
```less
._lib-column-width(@_width, @_check, @_index) when (@_check = true), (@_width = auto) {
    .lib-css(width, @_width);
    @_index: 1;
}
```

```less
& when (@media-target = 'mobile'), (@media-target = 'all') {
    @media only screen and (max-width: (@screen__xxs - 1)) {
        .media-width('max', @screen__xxs);
    }
}
```

Replacing `,` with `and` or removing the second condition is fixing an issue.

Stack trace:
```
TypeError: Cannot read property 'value' of undefined
    at Parser.parentheses (/Users/igloczek/.nvm/versions/node/v6.10.3/lib/node_modules/lesshint/node_modules/postcss-selector-parser/dist/parser.js:309:17)
    at Parser.parse (/Users/igloczek/.nvm/versions/node/v6.10.3/lib/node_modules/lesshint/node_modules/postcss-selector-parser/dist/parser.js:533:22)
    at Parser.loop (/Users/igloczek/.nvm/versions/node/v6.10.3/lib/node_modules/lesshint/node_modules/postcss-selector-parser/dist/parser.js:519:18)
    at new Parser (/Users/igloczek/.nvm/versions/node/v6.10.3/lib/node_modules/lesshint/node_modules/postcss-selector-parser/dist/parser.js:104:21)
    at Processor.process (/Users/igloczek/.nvm/versions/node/v6.10.3/lib/node_modules/lesshint/node_modules/postcss-selector-parser/dist/processor.js:26:21)
    at module.exports (/Users/igloczek/.nvm/versions/node/v6.10.3/lib/node_modules/lesshint/lib/utils/parse-selector.js:10:8)
    at Object.attributeQuotesLinter [as lint] (/Users/igloczek/.nvm/versions/node/v6.10.3/lib/node_modules/lesshint/lib/linters/attribute_quotes.js:15:27)
    at linters.forEach (/Users/igloczek/.nvm/versions/node/v6.10.3/lib/node_modules/lesshint/lib/linter.js:94:38)
    at Array.forEach (native)
    at Linter.checkNode (/Users/igloczek/.nvm/versions/node/v6.10.3/lib/node_modules/lesshint/lib/linter.js:81:22)
```

**Comment by jwilsson** [comment]
Hi!
It looks like you've run into [this issue over at postcss-selector-parser](https://github.com/postcss/postcss-selector-parser/issues/99). Please consider contributing a fix there, I don't think there's much we can do on our end.

**Comment by Igloczek** [comment]
Thanks for the answer, I'll check this out.
