### ISSUE TITLE
Exception on fresh install

### ISSUE THREAD

**Issue by matt-ball** [lesshint/lesshint#470]
**Which version of `lesshint` are you using?**
5.0.2 and Node v8.9.4

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?**
CLI

**What's your `.lesshintrc` configuration?**

```js
{
  "fileExtensions": [".less"],
  "excludedFiles": ["node_modules/*.less"],
  "colorVariables": false,
  "hexLength": false,
  "idSelector": false,
  "importantRule": {
    "enabled": true,
    "severity": "warning"
  },
  "maxCharPerLine": false,
  "propertyOrdering": false,
  "singleLinePerSelector": false,
  "urlFormat": false,
  "zeroUnit": false
}
```

**To recreate**
`npm install lesshint --save-dev`
..created .lesshintrc..
`node_modules/.bin/lesshint .`

**What's the actual result?**
```
An unknown error occurred when checking "/Users/mattball/Documents/dev/experiences/node_modules/lesshint/test/data/old-inline-options/options-invalid.less", please file an issue with this info:
Error: Invalid inline option on line 1
    at Linter.parseOption (/Users/mattball/Documents/dev/experiences/node_modules/lesshint/lib/linter.js:331:19)
    at ast.root.walkComments (/Users/mattball/Documents/dev/experiences/node_modules/lesshint/lib/linter.js:150:33)
    at /Users/mattball/Documents/dev/experiences/node_modules/postcss-less/node_modules/postcss/lib/container.js:335:24
    at /Users/mattball/Documents/dev/experiences/node_modules/postcss-less/node_modules/postcss/lib/container.js:148:26
    at Root.each (/Users/mattball/Documents/dev/experiences/node_modules/postcss-less/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/Users/mattball/Documents/dev/experiences/node_modules/postcss-less/node_modules/postcss/lib/container.js:147:21)
    at Root.walkComments (/Users/mattball/Documents/dev/experiences/node_modules/postcss-less/node_modules/postcss/lib/container.js:333:21)
    at Linter.configure (/Users/mattball/Documents/dev/experiences/node_modules/lesshint/lib/linter.js:149:23)
    at new Linter (/Users/mattball/Documents/dev/experiences/node_modules/lesshint/lib/linter.js:77:14)
    at Lesshint.checkString (/Users/mattball/Documents/dev/experiences/node_modules/lesshint/lib/lesshint.js:43:28)
```

Deleting `options-invalid.less` resolves the issue, however `.lesshintrc` appears to be ignored even if I specify the path to it as files within `node_modules` are ran through the linter.

**Comment by jwilsson** [comment]
Hi! 
Thanks for the report!

I think I managed to track it down to a change with our globbing package `globby` and a change there. It should be fixed on our side now though, and I'll tag a new release in a few minutes fixing it.

**Comment by jwilsson** [comment]
Alright, I found the issue (and I'm a bit embarrassed for not seeing it earlier).

Switch the `excludedFiles` option to `node_modules/**/*.less`, cause the current glob pattern will only match `.less`-files on the first level of `node_modules`, not ones further down.
